name = "deyxpress1"
main = "index.js" # O la ruta a tu archivo principal, ej: "src/index.ts"
compatibility_date = "2026-01-31"

name = "deyxpress1"
main = "index.js"
compatibility_date = "2026-01-31"

[rules]
identifiers = [ "HTML" ]
type = "Text"
globs = [ "**/*.html" ]
